# Generated by Django 4.1.5 on 2024-01-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.CharField(default=2024, max_length=256),
        ),
    ]
