# Generated by Django 4.1.5 on 2024-01-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default=2024, max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.CharField(default=150, max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 6, 18, 8, 697915, tzinfo=datetime.timezone.utc)),
        ),
    ]
