# Generated by Django 4.1.5 on 2024-01-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_isbn_product_pages_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(default=545454, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 6, 18, 45, 899804, tzinfo=datetime.timezone.utc)),
        ),
    ]
