# Generated by Django 4.1.5 on 2024-01-10 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_isbn_alter_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default=5, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 6, 21, 32, 907165, tzinfo=datetime.timezone.utc)),
        ),
    ]
