# Generated by Django 4.1.5 on 2024-01-10 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_stock_alter_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='este es el autor', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 6, 25, 48, 601845, tzinfo=datetime.timezone.utc)),
        ),
    ]
