# Generated by Django 4.1.5 on 2024-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_description_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deposit',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
