# Generated by Django 4.1.5 on 2024-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_deposit_alter_product_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
